### ISSUE TITLE
Not compatible with Robolectric > 3.2

### ISSUE THREAD

**Issue by ysyyork** [anggrayudi/android-hidden-api#48]
Tested on API level 25 and 26, if I'm using Robolectric 3.2, it's still working. But for some reason that version is not compatible with powermock. Then I upgrade to 3.3 it stops working by raising very weird error like below:
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -3

	at java.lang.String.substring(String.java:1931)
	at org.robolectric.res.ResourceTableFactory.addMissingStyleableAttributes(ResourceTableFactory.java:88)
	at org.robolectric.res.ResourceTableFactory.newFrameworkResourceTable(ResourceTableFactory.java:17)
	at org.robolectric.RobolectricTestRunner.getCompiletimeSdkResourceTable(RobolectricTestRunner.java:243)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:293)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:222)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:110)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:64)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```
If I switch SDK back to the original one, it will work perfect. I test 3.3, 3.4 to 4.0 (latest) of robolectric and non of them works.

**Comment by anggrayudi** [comment]
Closing as obsolete — this targets a long-superseded toolchain (Robolectric 3.2 with PowerMock). The project has since moved to AGP 9 / SDK 37, and the prebuilt Google Drive jars are deprecated in favor of the **`hiddenjar`** CLI, which builds a fresh `android.jar` for your API level:

```bash
./cli/hiddenjar build --api <level>          # macOS/Linux
# Windows: powershell -ExecutionPolicy Bypass -File cli\hiddenjar.ps1 build --api <level>
# any OS:  ./gradlew buildHiddenJar -Papi=<level>
```

Reopen if you still reproduce this on current tooling.
